# Generated by Django 3.0.6 on 2020-05-25 01:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=150)),
                ('service_description', models.TextField(max_length=150)),
                ('service_images', models.ImageField(blank=True, null=True, upload_to='img_services')),
                ('service_status', models.CharField(default='A', max_length=1)),
                ('service_open', models.DateTimeField(default=datetime.datetime.now)),
                ('service_closed', models.DateTimeField(null=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.ServicesCategory')),
                ('service_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.Community')),
                ('service_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
