# Generated by Django 3.0.6 on 2020-05-31 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='community_data',
            new_name='community_address',
        ),
    ]
